locale: "en-US"
title: Minglu (Lucy) Zhao # Title of your site
url: "https://lucyzhao1999.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: ""

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  Personal Website of Minglu (Lucy) Zhao, 3rd year student at University of California, Los Angeles (UCLA), double majoring in Statistics and Cognitive Science (with a specialization in Computing), with a minor in Mathematics

# Author details for the jekyll-seo-tag gem
author:
  name: Minglu Lucy Zhao
  email: mz517@g.ucla.edu
  twitter: lucywatermelon1 # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Strata Reloaded Template
  links:
    - https://github.com/comfusion/strata-reloaded-jekyll-template

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
